name: maporizer
root: ~/dev/maporizer

windows:
  - main:
      layout: even-horizontal
      panes:
        - ls maporizer.xsl | entr -cr bash -c "java -jar saxon.jar -s:map.xml -xsl:maporizer.xsl -o:map.svg && echo done"
        -
