name: maporizer
root: ~/dev/maporizer

windows:
  - main:
      layout: even-horizontal
      panes:
        - ls maporizer.xsl | entr -cr bash -c "time java -jar saxon.jar -s:peckhamXL3.xml -xsl:maporizer.xsl -o:peckham.svg title='P E C K H A M' && echo done"
        -
